services:
  - type: web
    name: notes-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DB_PATH
        value: /opt/render/project/src/notes.db
      - key: NODE_ENV
        value: production
